"""Synthetic documents for the "Founder Arrival" demo persona.

Fictional people, a fictional company and an obviously fake passport number, printed as
real PDFs with a text layer. Every page says SPECIMEN in a banner, a footer and a diagonal
watermark, and carries no emblem or security feature of any real document.

The values are printed so that nothing is ambiguous to the reader (day above 12, month
names, explicit yes/no words), which keeps the demo free of review gates. What each line
means to ADAPT is documented in docs/demo-founder-arrival.md.

    uv run python -m app.demo_scenarios.documents ../demo-documents/founder-arrival
"""

from __future__ import annotations

import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from app.demo_scenarios.pdf import (
    MUTED,
    NAVY,
    PAPER,
    RED,
    RULE,
    SLATE,
    TEAL,
    TINT,
    WHITE,
    WIDTH,
    Canvas,
)
from app.documents.mrz import build_td3

BANNER = "SPECIMEN - SYNTHETIC DEMO DOCUMENT - NOT VALID FOR ANY PURPOSE"
FOOTER = "Generated by ADAPT for a demonstration. The people, numbers and company are fictional."


@dataclass(frozen=True, slots=True)
class Persona:
    surname: str = "RAHMAN"
    given_names: str = "KABIR"
    date_of_birth: date = date(1991, 7, 18)
    spouse_name: str = "Ayesha Rahman"
    spouse_date_of_birth: date = date(1994, 3, 14)
    passport_number: str = "Z0000000"  # obviously not a real number
    passport_issued: date = date(2024, 2, 14)
    passport_expiry: date = date(2034, 2, 13)
    married_on: date = date(2021, 2, 6)
    company: str = "Noorvia Labs Ltd"

    @property
    def full_name(self) -> str:
        return f"{self.given_names.title()} {self.surname.title()}"


PERSONA = Persona()
LEFT = 56


def _long(day: date) -> str:
    return f"{day.day} {day.strftime('%B %Y')}"


def _frame(c: Canvas, title: str, subtitle: str) -> float:
    """Paper, the SPECIMEN band and a navy header. Returns the y to continue from."""
    c.rect(0, 0, WIDTH, 842, fill=PAPER)
    c.rect(28, 28, WIDTH - 56, 786, stroke=RULE, width=1.2)
    c.rect(28, 790, WIDTH - 56, 24, fill=RED)
    c.text(LEFT, 798, BANNER, size=10, font="bold", colour=WHITE)
    c.rect(28, 712, WIDTH - 56, 78, fill=NAVY)
    c.rect(28, 708, WIDTH - 56, 4, fill=TEAL)
    c.text(LEFT, 756, title, size=20, font="bold", colour=WHITE)
    c.text(LEFT, 730, subtitle, size=10.5, colour=(0.80, 0.86, 0.92))
    return 680


def _footer(c: Canvas) -> None:
    c.line(LEFT, 62, WIDTH - LEFT, 62)
    c.text(LEFT, 46, FOOTER, size=8, colour=MUTED)
    c.watermark("SPECIMEN")


def _section(c: Canvas, y: float, heading: str) -> float:
    c.text(LEFT, y, heading.upper(), size=8.5, font="bold", colour=TEAL)
    c.line(LEFT, y - 6, WIDTH - LEFT, y - 6)
    return y - 26


def _fields(c: Canvas, y: float, rows: list[str], *, step: float = 22, width: float = 0) -> float:
    """One `Label: value` run per line, each on its own baseline."""
    right = width or (WIDTH - LEFT * 2)
    for index, row in enumerate(rows):
        if index % 2 == 0:
            c.rect(LEFT - 6, y - 7, right + 12, step, fill=TINT)
        c.text(LEFT, y, row)
        y -= step
    return y


def passport(p: Persona = PERSONA) -> bytes:
    line1, line2 = build_td3(
        issuing_country="IND",
        surname=p.surname,
        given_names=p.given_names,
        document_number=p.passport_number,
        nationality="IND",
        date_of_birth=p.date_of_birth,
        sex="M",
        expiry_date=p.passport_expiry,
    )
    c = Canvas()
    y = _frame(
        c,
        "REPUBLIC OF INDIA - PASSPORT",
        "Specimen photo page. Synthetic data for a relocation demo.",
    )
    c.silhouette(WIDTH - LEFT - 132, 470, 132, 170)
    y = _section(c, y, "Holder")
    y = _fields(
        c,
        y,
        [
            "Type: P",
            f"Passport No.: {p.passport_number}",
            f"Surname: {p.surname}",
            f"Given names: {p.given_names}",
            "Nationality: INDIAN",
            "Sex: M",
            f"Date of birth: {p.date_of_birth.strftime('%d/%m/%Y')}",
            "Place of birth: LUCKNOW",
        ],
        width=300,
    )
    y = _section(c, y - 14, "Document")
    _fields(
        c,
        y,
        [
            f"Date of issue: {p.passport_issued.strftime('%d/%m/%Y')}",
            f"Date of expiry: {p.passport_expiry.strftime('%d/%m/%Y')}",
            "Country code: IND",
        ],
        width=300,
    )
    c.rect(28, 92, WIDTH - 56, 74, fill=(0.93, 0.93, 0.90))
    c.text(LEFT, 140, line1, size=11.5, font="mono", colour=NAVY)
    c.text(LEFT, 114, line2, size=11.5, font="mono", colour=NAVY)
    _footer(c)
    return c.render()


def marriage_certificate(p: Persona = PERSONA) -> bytes:
    c = Canvas()
    y = _frame(
        c,
        "MARRIAGE CERTIFICATE",
        "Extract of marriage registration. Synthetic record for a relocation demo.",
    )
    y = _section(c, y, "Registration")
    y = _fields(
        c,
        y,
        [
            "Registration number: SPECIMEN-0000-2021",
            f"Date of marriage: {_long(p.married_on)}",
            "Country of marriage: India",
            "Registrar: Registrar of Marriages, Bengaluru Urban District",
        ],
    )
    y = _section(c, y - 14, "Parties")
    y = _fields(
        c,
        y,
        [
            f"Husband: {p.full_name}",
            f"Husband's date of birth: {_long(p.date_of_birth)}",
            f"Wife: {p.spouse_name}",
            f"Wife's date of birth: {_long(p.spouse_date_of_birth)}",
        ],
    )
    y = _section(c, y - 14, "Attestation")
    y = _fields(
        c,
        y,
        [
            "Home country attestation: Attested",
            "Attested by: Ministry of External Affairs, Government of India",
            "UAE attestation: Not attested",
        ],
    )
    c.rect(WIDTH - LEFT - 150, 96, 150, 64, stroke=SLATE, width=1.4)
    c.text(WIDTH - LEFT - 138, 136, "SPECIMEN SEAL", size=9, font="bold", colour=SLATE)
    c.text(WIDTH - LEFT - 138, 118, "No legal effect", size=8, colour=MUTED)
    _footer(c)
    return c.render()


def business_profile(p: Persona = PERSONA) -> bytes:
    c = Canvas()
    y = _frame(
        c,
        "BUSINESS PROFILE",
        f"Business plan summary - {p.company}. Prepared by the founder for relocation planning.",
    )
    y = _section(c, y, "Company")
    y = _fields(
        c,
        y,
        [
            "Document: Business profile and business plan summary",
            f"Company name: {p.company}",
            "Legal form: Private company limited by shares",
            "Planned jurisdiction: ADGM (Abu Dhabi Global Market)",
            "Business activities: Software development; Artificial intelligence solutions",
            "Stage: Pre-incorporation, not yet registered",
        ],
    )
    y = _section(c, y - 14, "Founder")
    y = _fields(
        c,
        y,
        [
            f"Founder and director: {p.full_name}",
            f"Shareholding: {p.full_name}, 100 percent",
            "Founder remuneration: To be decided by the board",
        ],
    )
    y = _section(c, y - 14, "First year")
    _fields(
        c,
        y,
        [
            "Office: Shared workspace in Abu Dhabi (planned)",
            "First hires: Three engineers",
            "Customers: Logistics companies in the Gulf region",
        ],
    )
    _footer(c)
    return c.render()


@dataclass(frozen=True, slots=True)
class SyntheticDocument:
    key: str
    kind: str  # DocumentKind value used for the upload
    filename: str
    title: str
    build: Callable[[], bytes]


DOCUMENTS: tuple[SyntheticDocument, ...] = (
    SyntheticDocument("passport", "passport", "passport-kabir-rahman.pdf", "Passport", passport),
    SyntheticDocument(
        "marriage_certificate",
        "marriage_certificate",
        "marriage-certificate-rahman.pdf",
        "Marriage certificate",
        marriage_certificate,
    ),
    SyntheticDocument(
        "business_profile",
        "business_document",
        "business-profile-noorvia-labs.pdf",
        "Business profile",
        business_profile,
    ),
)
BY_KEY = {d.key: d for d in DOCUMENTS}


def main(argv: list[str]) -> int:
    target = Path(argv[1] if len(argv) > 1 else "founder-arrival")
    target.mkdir(parents=True, exist_ok=True)
    for doc in DOCUMENTS:
        (target / doc.filename).write_bytes(doc.build())
        print(target / doc.filename)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
