"""initial schema: accounts, knowledge graphs, RAG corpus, private user data, RLS

Everything below the autogenerated block is hand-written security:
* RLS context functions and owner-only policies on every private table;
* governance-readable / twin-owner-only policies on the graph tables;
* a trigger that stops governance edges from touching private twin nodes;
* grants for the non-owner runtime role; a schema for LangGraph checkpoints.

Revision ID: 0001
Revises:
Create Date: 2026-09-29 10:56:10.328167+00:00
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db import rls

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Frozen copies of what this revision created. Migrations must not depend on mutable
# application code: later revisions changed the models, the private-table list and the
# graph policies, so revision 0001 keeps its own definitions. Revision 0002's downgrade
# calls `create_content_tables()` / `secure_content_tables()` to restore this schema.
PRIVATE_TABLES_0001: tuple[str, ...] = (
    "documents",
    "journeys",
    "journey_steps",
    "agent_runs",
    "run_events",
    "approvals",
    "actions",
    "research_findings",
    "drafts",
)
GRAPH_TABLES_0001: tuple[str, ...] = ("graph_nodes", "graph_edges")
PUBLIC_TABLES_0001: tuple[str, ...] = ("rag_sources", "rag_chunks", "graph_node_evidence")

_TWIN_OWNED = f"scope = 'twin' AND {rls.OWNER_PREDICATE}"

GRAPH_EDGE_SCOPE_TRIGGER_SQL_0001 = """
CREATE OR REPLACE FUNCTION graph_edges_enforce_scope() RETURNS trigger
  LANGUAGE plpgsql AS $$
DECLARE
  s_scope text; s_user uuid;
  t_scope text; t_user uuid;
BEGIN
  SELECT scope, user_id INTO s_scope, s_user FROM graph_nodes WHERE id = NEW.source_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'graph edge source % not found', NEW.source_id USING ERRCODE = 'check_violation';
  END IF;
  SELECT scope, user_id INTO t_scope, t_user FROM graph_nodes WHERE id = NEW.target_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'graph edge target % not found', NEW.target_id USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.scope = 'governance' THEN
    IF s_scope <> 'governance' OR t_scope <> 'governance' THEN
      RAISE EXCEPTION 'governance edges may only connect governance nodes'
        USING ERRCODE = 'check_violation';
    END IF;
  ELSE
    IF s_scope <> 'twin' OR s_user IS DISTINCT FROM NEW.user_id THEN
      RAISE EXCEPTION 'twin edges must start at a twin node owned by the same user'
        USING ERRCODE = 'check_violation';
    END IF;
    IF t_scope = 'twin' AND t_user IS DISTINCT FROM NEW.user_id THEN
      RAISE EXCEPTION 'twin edges may not point at another user''s twin node'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER graph_edges_enforce_scope
  BEFORE INSERT OR UPDATE ON graph_edges
  FOR EACH ROW EXECUTE FUNCTION graph_edges_enforce_scope();
"""


def _graph_table_sql_0001(table: str) -> list[str]:
    role = rls.app_role()
    return [
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
        f"CREATE POLICY {table}_read ON {table} FOR SELECT "
        f"USING (scope = 'governance' OR ({_TWIN_OWNED}))",
        f"CREATE POLICY {table}_write_twin ON {table} FOR ALL "
        f"USING ({_TWIN_OWNED}) WITH CHECK ({_TWIN_OWNED})",
        rls.if_role_exists(role, f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {role}"),
    ]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(rls.CONTEXT_FUNCTIONS_SQL)
    _create_accounts()
    create_content_tables()
    secure_content_tables()
    statements: list[str] = []
    for table in ("tenants", "users"):
        statements += rls.account_table_sql(table)
    statements += rls.sequences_grant_sql()
    statements += rls.langgraph_schema_sql()
    for statement in statements:
        op.execute(statement)


def _create_accounts() -> None:
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "users",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)


def create_content_tables() -> None:
    """Graph, RAG corpus and private tables of this revision (autogenerated DDL)."""
    op.create_table(
        "rag_sources",
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("source_title", sa.String(length=500), nullable=False),
        sa.Column("authority", sa.String(length=200), nullable=True),
        sa.Column("document_type", sa.String(length=60), nullable=False),
        sa.Column("language", sa.String(length=35), server_default="en", nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_sources")),
        sa.UniqueConstraint("source_url", "content_hash", name="uq_rag_sources_url_hash"),
    )
    op.create_index("ix_rag_sources_authority", "rag_sources", ["authority"], unique=False)
    op.create_index(
        "uq_rag_sources_live_url",
        "rag_sources",
        ["source_url"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_table(
        "rag_chunks",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("section", sa.String(length=500), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', content)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["rag_sources.id"],
            name=op.f("fk_rag_chunks_source_id_rag_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_chunks")),
        sa.UniqueConstraint("source_id", "chunk_index", name="uq_rag_chunks_source_index"),
    )
    op.create_index(
        "ix_rag_chunks_content_tsv",
        "rag_chunks",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_rag_chunks_embedding",
        "rag_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_rag_chunks_source_id"), "rag_chunks", ["source_id"], unique=False)
    op.create_table(
        "graph_nodes",
        sa.Column(
            "scope",
            sa.Enum("governance", "twin", name="graphscope", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("node_type", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("official_url", sa.String(length=2048), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'governance' AND node_type IN ('authority', 'service', 'requirement', 'document_type', 'eligibility_rule', 'process_step', 'fee', 'official_channel', 'legal_instrument', 'location')) OR (scope = 'twin' AND node_type IN ('person', 'organization', 'document', 'goal', 'preference', 'constraint', 'milestone'))",
            name=op.f("ck_graph_nodes_node_type_matches_scope"),
        ),
        sa.CheckConstraint(
            "(scope = 'governance' AND tenant_id IS NULL AND user_id IS NULL) OR (scope = 'twin' AND tenant_id IS NOT NULL AND user_id IS NOT NULL)",
            name=op.f("ck_graph_nodes_ownership_matches_scope"),
        ),
        sa.CheckConstraint(
            "key ~ '^[a-z0-9_]+(\\.[a-z0-9_:-]+)*$'", name=op.f("ck_graph_nodes_key_format")
        ),
        sa.CheckConstraint(
            "scope IN ('governance', 'twin')", name=op.f("ck_graph_nodes_scope_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_graph_nodes_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_graph_nodes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_nodes")),
    )
    op.create_index(
        "ix_graph_nodes_embedding",
        "graph_nodes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_graph_nodes_properties",
        "graph_nodes",
        ["properties"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_graph_nodes_scope_type", "graph_nodes", ["scope", "node_type"], unique=False
    )
    op.create_index(op.f("ix_graph_nodes_user_id"), "graph_nodes", ["user_id"], unique=False)
    op.create_index(
        "uq_graph_nodes_governance_key",
        "graph_nodes",
        ["key"],
        unique=True,
        postgresql_where=sa.text("scope = 'governance'"),
    )
    op.create_index(
        "uq_graph_nodes_twin_key",
        "graph_nodes",
        ["user_id", "key"],
        unique=True,
        postgresql_where=sa.text("scope = 'twin'"),
    )
    op.create_table(
        "journeys",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "scenario",
                "archived",
                name="journeystatus",
                native_enum=False,
                length=40,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "goals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "assumptions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "considerations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("parent_journey_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'scenario', 'archived')",
            name=op.f("ck_journeys_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_journey_id"],
            ["journeys.id"],
            name=op.f("fk_journeys_parent_journey_id_journeys"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_journeys_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_journeys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journeys")),
    )
    op.create_index(op.f("ix_journeys_user_id"), "journeys", ["user_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column(
            "kind",
            sa.Enum(
                "journey",
                "what_if",
                "research",
                "document_extraction",
                "drafting",
                "diagnostic",
                name="runkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "awaiting_input",
                "succeeded",
                "failed",
                "cancelled",
                name="runstatus",
                native_enum=False,
                length=40,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("journey_id", sa.UUID(), nullable=True),
        sa.Column("thread_id", sa.String(length=100), nullable=False),
        sa.Column(
            "input",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("event_seq", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("job_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('journey', 'what_if', 'research', 'document_extraction', 'drafting', 'diagnostic')",
            name=op.f("ck_agent_runs_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'awaiting_input', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_agent_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["journeys.id"],
            name=op.f("fk_agent_runs_journey_id_journeys"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_agent_runs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint("thread_id", name=op.f("uq_agent_runs_thread_id")),
    )
    op.create_index(
        "ix_agent_runs_user_created", "agent_runs", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_user_id"), "agent_runs", ["user_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column(
            "kind",
            sa.Enum(
                "passport",
                "marriage_certificate",
                "emirates_id",
                "residence_visa",
                "degree_certificate",
                "tenancy_contract",
                "trade_license",
                "bank_statement",
                "photo",
                "other",
                name="documentkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "extracted",
                "needs_review",
                "confirmed",
                "failed",
                name="documentstatus",
                native_enum=False,
                length=40,
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("twin_node_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('passport', 'marriage_certificate', 'emirates_id', 'residence_visa', 'degree_certificate', 'tenancy_contract', 'trade_license', 'bank_statement', 'photo', 'other')",
            name=op.f("ck_documents_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded', 'processing', 'extracted', 'needs_review', 'confirmed', 'failed')",
            name=op.f("ck_documents_status_valid"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_documents_size_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_documents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["twin_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_documents_twin_node_id_graph_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_documents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
    )
    op.create_index(op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False)
    op.create_table(
        "graph_edges",
        sa.Column(
            "scope",
            sa.Enum("governance", "twin", name="graphscope", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "edge_type",
            sa.Enum(
                "provided_by",
                "requires",
                "depends_on",
                "produces",
                "applies_to",
                "available_via",
                "governed_by",
                "located_in",
                "spouse_of",
                "dependent_of",
                "founder_of",
                "holds_document",
                "has_goal",
                "prefers",
                "constrained_by",
                "pursues",
                "satisfies",
                "instance_of",
                "eligible_for",
                "blocked_by",
                name="graphedgetype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(scope = 'governance' AND tenant_id IS NULL AND user_id IS NULL) OR (scope = 'twin' AND tenant_id IS NOT NULL AND user_id IS NOT NULL)",
            name=op.f("ck_graph_edges_ownership_matches_scope"),
        ),
        sa.CheckConstraint(
            "edge_type IN ('provided_by', 'requires', 'depends_on', 'produces', 'applies_to', 'available_via', 'governed_by', 'located_in', 'spouse_of', 'dependent_of', 'founder_of', 'holds_document', 'has_goal', 'prefers', 'constrained_by', 'pursues', 'satisfies', 'instance_of', 'eligible_for', 'blocked_by')",
            name=op.f("ck_graph_edges_edge_type_valid"),
        ),
        sa.CheckConstraint(
            "scope IN ('governance', 'twin')", name=op.f("ck_graph_edges_scope_valid")
        ),
        sa.CheckConstraint("source_id <> target_id", name=op.f("ck_graph_edges_no_self_loops")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_source_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_target_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_graph_edges_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_graph_edges_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_edges")),
        sa.UniqueConstraint("source_id", "target_id", "edge_type", name="uq_graph_edges_triple"),
    )
    op.create_index(
        "ix_graph_edges_scope_type", "graph_edges", ["scope", "edge_type"], unique=False
    )
    op.create_index("ix_graph_edges_target", "graph_edges", ["target_id"], unique=False)
    op.create_index(op.f("ix_graph_edges_user_id"), "graph_edges", ["user_id"], unique=False)
    op.create_table(
        "graph_node_evidence",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["rag_chunks.id"],
            name=op.f("fk_graph_node_evidence_chunk_id_rag_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_node_evidence_node_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["rag_sources.id"],
            name=op.f("fk_graph_node_evidence_source_id_rag_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_node_evidence")),
        sa.UniqueConstraint("node_id", "chunk_id", name="uq_graph_node_evidence_node_chunk"),
    )
    op.create_index(
        op.f("ix_graph_node_evidence_node_id"), "graph_node_evidence", ["node_id"], unique=False
    )
    op.create_table(
        "journey_steps",
        sa.Column("journey_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "business",
                "residency",
                "family",
                "housing",
                "health",
                "finance",
                "daily_life",
                "community",
                name="stepcategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "blocked",
                "needs_info",
                "ready",
                "in_progress",
                "awaiting_approval",
                "handoff",
                "done",
                "not_applicable",
                name="stepstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "depends_on",
            postgresql.ARRAY(sa.String(length=120)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("governance_node_id", sa.UUID(), nullable=True),
        sa.Column("authority", sa.String(length=200), nullable=True),
        sa.Column("official_url", sa.String(length=2048), nullable=True),
        sa.Column("estimated_duration_days", sa.Integer(), nullable=True),
        sa.Column("due_by", sa.Date(), nullable=True),
        sa.Column(
            "blockers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "category IN ('business', 'residency', 'family', 'housing', 'health', 'finance', 'daily_life', 'community')",
            name=op.f("ck_journey_steps_category_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('blocked', 'needs_info', 'ready', 'in_progress', 'awaiting_approval', 'handoff', 'done', 'not_applicable')",
            name=op.f("ck_journey_steps_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["governance_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_journey_steps_governance_node_id_graph_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["journeys.id"],
            name=op.f("fk_journey_steps_journey_id_journeys"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_journey_steps_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_journey_steps_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journey_steps")),
        sa.UniqueConstraint("journey_id", "key", name="uq_journey_steps_journey_key"),
    )
    op.create_index(
        op.f("ix_journey_steps_journey_id"), "journey_steps", ["journey_id"], unique=False
    )
    op.create_index(op.f("ix_journey_steps_user_id"), "journey_steps", ["user_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "action_kind",
            sa.Enum(
                "official_handoff",
                "appointment",
                "submission",
                "communication",
                name="actionkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "consequences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "payload_preview",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "requires_user_authentication",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "expired",
                name="approvalstatus",
                native_enum=False,
                length=40,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(status = 'pending') = (decided_at IS NULL)",
            name=op.f("ck_approvals_decided_at_matches_status"),
        ),
        sa.CheckConstraint(
            "action_kind IN ('official_handoff', 'appointment', 'submission', 'communication')",
            name=op.f("ck_approvals_action_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired')",
            name=op.f("ck_approvals_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_approvals_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_approvals_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_approvals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_index(op.f("ix_approvals_user_id"), "approvals", ["user_id"], unique=False)
    op.create_table(
        "drafts",
        sa.Column("journey_id", sa.UUID(), nullable=True),
        sa.Column("journey_step_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "cover_letter",
                "email",
                "checklist",
                "form_prefill",
                "business_summary",
                name="draftkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('cover_letter', 'email', 'checklist', 'form_prefill', 'business_summary')",
            name=op.f("ck_drafts_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'discarded')", name=op.f("ck_drafts_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["journeys.id"],
            name=op.f("fk_drafts_journey_id_journeys"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["journey_step_id"],
            ["journey_steps.id"],
            name=op.f("fk_drafts_journey_step_id_journey_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_drafts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_drafts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
    )
    op.create_index(op.f("ix_drafts_user_id"), "drafts", ["user_id"], unique=False)
    op.create_table(
        "research_findings",
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "community",
                "event",
                "culture",
                "practical",
                "faith",
                name="researchcategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("source_title", sa.String(length=500), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "evidence_kind", sa.String(length=40), server_default="community_web", nullable=False
        ),
        sa.Column("relevance", sa.Text(), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "category IN ('community', 'event', 'culture', 'practical', 'faith')",
            name=op.f("ck_research_findings_category_valid"),
        ),
        sa.CheckConstraint(
            "evidence_kind = 'community_web'",
            name=op.f("ck_research_findings_web_findings_are_not_authoritative"),
        ),
        sa.CheckConstraint(
            "starts_with(source_url, 'http')", name=op.f("ck_research_findings_source_url_present")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_research_findings_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_research_findings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_research_findings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_findings")),
    )
    op.create_index(
        "ix_research_findings_user_category",
        "research_findings",
        ["user_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_findings_user_id"), "research_findings", ["user_id"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("node", sa.String(length=80), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_run_events_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_run_events_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_run_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_events_run_seq"),
    )
    op.create_index(op.f("ix_run_events_user_id"), "run_events", ["user_id"], unique=False)
    op.create_table(
        "actions",
        sa.Column("approval_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("journey_step_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "official_handoff",
                "appointment",
                "submission",
                "communication",
                name="actionkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("adapter", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "prepared",
                "awaiting_approval",
                "handoff_ready",
                "submitted",
                "confirmed",
                "failed",
                "cancelled",
                name="actionstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("handoff_url", sa.String(length=2048), nullable=True),
        sa.Column("external_reference", sa.String(length=200), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column(
            "request",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "response_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('official_handoff', 'appointment', 'submission', 'communication')",
            name=op.f("ck_actions_kind_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'confirmed' OR (external_reference IS NOT NULL AND NOT is_simulated)",
            name=op.f("ck_actions_confirmed_requires_real_reference"),
        ),
        sa.CheckConstraint(
            "status <> 'handoff_ready' OR starts_with(handoff_url, 'https://')",
            name=op.f("ck_actions_handoff_requires_url"),
        ),
        sa.CheckConstraint(
            "status IN ('prepared', 'awaiting_approval', 'handoff_ready', 'submitted', 'confirmed', 'failed', 'cancelled')",
            name=op.f("ck_actions_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('submitted', 'confirmed') OR (approval_id IS NOT NULL AND NOT is_simulated)",
            name=op.f("ck_actions_submission_requires_approval"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_actions_approval_id_approvals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journey_step_id"],
            ["journey_steps.id"],
            name=op.f("fk_actions_journey_step_id_journey_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_actions_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_actions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_actions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
    )
    op.create_index(op.f("ix_actions_user_id"), "actions", ["user_id"], unique=False)


def secure_content_tables() -> None:
    op.execute(GRAPH_EDGE_SCOPE_TRIGGER_SQL_0001)
    statements: list[str] = []
    for table in PRIVATE_TABLES_0001:
        statements += rls.private_table_sql(table)
    for table in GRAPH_TABLES_0001:
        statements += _graph_table_sql_0001(table)
    for table in PUBLIC_TABLES_0001:
        statements += rls.public_read_sql(table)
    for statement in statements:
        op.execute(statement)


def drop_content_tables() -> None:
    op.drop_index(op.f("ix_actions_user_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_run_events_user_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_research_findings_user_id"), table_name="research_findings")
    op.drop_index("ix_research_findings_user_category", table_name="research_findings")
    op.drop_table("research_findings")
    op.drop_index(op.f("ix_drafts_user_id"), table_name="drafts")
    op.drop_table("drafts")
    op.drop_index(op.f("ix_approvals_user_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_journey_steps_user_id"), table_name="journey_steps")
    op.drop_index(op.f("ix_journey_steps_journey_id"), table_name="journey_steps")
    op.drop_table("journey_steps")
    op.drop_index(op.f("ix_graph_node_evidence_node_id"), table_name="graph_node_evidence")
    op.drop_table("graph_node_evidence")
    op.drop_index(op.f("ix_graph_edges_user_id"), table_name="graph_edges")
    op.drop_index("ix_graph_edges_target", table_name="graph_edges")
    op.drop_index("ix_graph_edges_scope_type", table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_agent_runs_user_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_user_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_journeys_user_id"), table_name="journeys")
    op.drop_table("journeys")
    op.drop_index(
        "uq_graph_nodes_twin_key",
        table_name="graph_nodes",
        postgresql_where=sa.text("scope = 'twin'"),
    )
    op.drop_index(
        "uq_graph_nodes_governance_key",
        table_name="graph_nodes",
        postgresql_where=sa.text("scope = 'governance'"),
    )
    op.drop_index(op.f("ix_graph_nodes_user_id"), table_name="graph_nodes")
    op.drop_index("ix_graph_nodes_scope_type", table_name="graph_nodes")
    op.drop_index("ix_graph_nodes_properties", table_name="graph_nodes", postgresql_using="gin")
    op.drop_index(
        "ix_graph_nodes_embedding",
        table_name="graph_nodes",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("graph_nodes")
    op.drop_index(op.f("ix_rag_chunks_source_id"), table_name="rag_chunks")
    op.drop_index(
        "ix_rag_chunks_embedding",
        table_name="rag_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_rag_chunks_content_tsv", table_name="rag_chunks", postgresql_using="gin")
    op.drop_table("rag_chunks")
    op.drop_index(
        "uq_rag_sources_live_url",
        table_name="rag_sources",
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index("ix_rag_sources_authority", table_name="rag_sources")
    op.drop_table("rag_sources")
    op.execute("DROP FUNCTION IF EXISTS graph_edges_enforce_scope() CASCADE;")


def downgrade() -> None:
    drop_content_tables()
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
    op.execute(rls.DROP_CONTEXT_FUNCTIONS_SQL)
